### ISSUE TITLE
Nicer Portals 1.5.0 crashes on start on with MC version 1.20.1

### ISSUE THREAD

**Issue by NolanHewitt** [Roundaround/mc-fabric-nicer-portals#13]
Title. The previous 1.20.1 version (1.2.1) works just fine.

**Comment by bons66** [comment]
Сonfirm
[crash.txt](https://github.com/user-attachments/files/17146168/crash.txt)

**Comment by Roundaround** [comment]
Okay, was able to update the metadata. Sorry for the trouble!
