### ISSUE TITLE
Crash when loading with Stackables

### ISSUE THREAD

**Issue by CaseyPurser** [Roundaround/mc-fabric-nicer-portals#3]
Was trying out the new updates for Nicer Portals and Stackables and found an issue where the game crashes when both are installed on Fabric. I tested each on their own and found no problems and did not need to clear any configs during my testing process.

Log: https://mclo.gs/EA6sd0N

**Comment by Roundaround** [comment]
Ah shoot. Luckily I think I know how I can fix this

**Comment by Roundaround** [comment]
Okay, issue should be fixed. Check out version 1.1.1 of both mods

Thanks so much for reporting! I'm glad we caught this issue early before I updated too many of the mods!
